'use server';

// =====================================================
// v0.47: HSE - SAFETY PERMIT SERVER ACTIONS
// =====================================================

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';
import {
  SafetyPermit,
  PermitStatistics,
  CreatePermitInput,
  PermitFilters,
  SafetyPermitRow,
  transformPermitRow,
} from '@/types/safety-document';
import { validatePermitInput } from './safety-document-utils';

// Type helper for tables not yet in database.types.ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyTable = any;

// Helper function to bypass type checking for safety permit tables
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const fromSafetyTable = (supabase: any, table: string) => supabase.from(table) as AnyTable;

// =====================================================
// PERMIT CRUD OPERATIONS
// =====================================================

/**
 * Create a new safety permit
 */
export async function createSafetyPermit(
  input: CreatePermitInput
): Promise<{ success: boolean; data?: SafetyPermit; error?: string }> {
  try {
    // Validate input
    const validation = validatePermitInput(input);
    if (!validation.valid) {
      return { success: false, error: validation.error };
    }

    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (employees.user_id references user_profiles.id)
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (!profile) {
      return { success: false, error: 'Profil pengguna tidak ditemukan. Silakan logout dan login kembali.' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile.id)
      .single();

    if (!employee) {
      return { success: false, error: 'Data karyawan tidak ditemukan. Hubungi HR atau administrator.' };
    }

    // Create permit (permit_number will be auto-generated by trigger)
    const { data: permit, error: insertError } = await fromSafetyTable(supabase, 'safety_permits')
      .insert({
        document_id: input.documentId || null,
        permit_type: input.permitType,
        work_description: input.workDescription,
        work_location: input.workLocation,
        job_order_id: input.jobOrderId || null,
        valid_from: input.validFrom,
        valid_to: input.validTo,
        special_precautions: input.specialPrecautions || null,
        required_ppe: input.requiredPPE || [],
        emergency_procedures: input.emergencyProcedures || null,
        requested_by: employee.id,
        requested_at: new Date().toISOString(),
        status: 'pending',
      })
      .select()
      .single();

    if (insertError) {
      console.error('Safety permit insert error:', insertError);
      return { success: false, error: `Gagal membuat izin kerja: ${insertError.message}` };
    }

    revalidatePath('/hse/permits');

    return {
      success: true,
      data: transformPermitRow(permit as SafetyPermitRow),
    };
  } catch (error) {
    console.error('createSafetyPermit error:', error);
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}


/**
 * Get a safety permit by ID
 */
export async function getSafetyPermit(
  id: string
): Promise<{ success: boolean; data?: SafetyPermit; error?: string }> {
  try {
    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'safety_permits')
      .select(`
        *,
        requester:employees!safety_permits_requested_by_fkey (full_name),
        supervisor:employees!safety_permits_supervisor_approved_by_fkey (full_name),
        hse:employees!safety_permits_hse_approved_by_fkey (full_name),
        closer:employees!safety_permits_closed_by_fkey (full_name),
        job_orders (jo_number),
        safety_documents (title)
      `)
      .eq('id', id)
      .single();

    if (error) {
      return { success: false, error: 'Izin kerja tidak ditemukan' };
    }

    // Transform the data
    const permit = transformPermitRow(data as SafetyPermitRow);
    
    // Add related data
    const requester = data.requester as { full_name: string } | null;
    const supervisor = data.supervisor as { full_name: string } | null;
    const hse = data.hse as { full_name: string } | null;
    const closer = data.closer as { full_name: string } | null;
    const jobOrder = data.job_orders as { jo_number: string } | null;
    const document = data.safety_documents as { title: string } | null;

    permit.requestedByName = requester?.full_name;
    permit.supervisorApprovedByName = supervisor?.full_name;
    permit.hseApprovedByName = hse?.full_name;
    permit.closedByName = closer?.full_name;
    permit.jobOrderNumber = jobOrder?.jo_number;
    permit.documentTitle = document?.title;

    return { success: true, data: permit };
  } catch (error) {
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

/**
 * Get safety permits list with filters
 */
export async function getSafetyPermits(
  filters: PermitFilters = {}
): Promise<{ success: boolean; data?: SafetyPermit[]; error?: string }> {
  try {
    const supabase = await createClient();

    let query = fromSafetyTable(supabase, 'safety_permits')
      .select(`
        *,
        requester:employees!safety_permits_requested_by_fkey (full_name),
        job_orders (jo_number)
      `)
      .order('created_at', { ascending: false });

    // Apply filters
    if (filters.status) {
      if (Array.isArray(filters.status)) {
        query = query.in('status', filters.status);
      } else {
        query = query.eq('status', filters.status);
      }
    }

    if (filters.permitType) {
      query = query.eq('permit_type', filters.permitType);
    }

    if (filters.jobOrderId) {
      query = query.eq('job_order_id', filters.jobOrderId);
    }

    if (filters.search) {
      query = query.or(`work_description.ilike.%${filters.search}%,permit_number.ilike.%${filters.search}%,work_location.ilike.%${filters.search}%`);
    }

    const { data, error } = await query;

    if (error) {
      return { success: false, error: 'Gagal mengambil daftar izin kerja' };
    }

    // Transform the data
    const permits = (data || []).map((row: SafetyPermitRow & { 
      requester: { full_name: string } | null;
      job_orders: { jo_number: string } | null;
    }) => {
      const permit = transformPermitRow(row as SafetyPermitRow);
      permit.requestedByName = row.requester?.full_name;
      permit.jobOrderNumber = row.job_orders?.jo_number;
      return permit;
    });

    return { success: true, data: permits };
  } catch (error) {
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

// =====================================================
// PERMIT APPROVAL FUNCTIONS
// =====================================================

/**
 * Approve permit by supervisor
 */
export async function approveBySupervisor(
  permitId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (employees.user_id references user_profiles.id)
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (!profile) {
      return { success: false, error: 'Profil pengguna tidak ditemukan' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile.id)
      .single();

    if (!employee) {
      return { success: false, error: 'Data karyawan tidak ditemukan' };
    }

    const { error } = await fromSafetyTable(supabase, 'safety_permits')
      .update({
        supervisor_approved_by: employee.id,
        supervisor_approved_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', permitId)
      .eq('status', 'pending')
      .is('supervisor_approved_by', null);

    if (error) {
      console.error('Supervisor approval error:', error);
      return { success: false, error: `Gagal menyetujui izin kerja: ${error.message}` };
    }

    revalidatePath('/hse/permits');
    revalidatePath(`/hse/permits/${permitId}`);

    return { success: true };
  } catch (error) {
    console.error('approveBySupervisor error:', error);
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

/**
 * Approve permit by HSE
 */
export async function approveByHSE(
  permitId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (employees.user_id references user_profiles.id)
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (!profile) {
      return { success: false, error: 'Profil pengguna tidak ditemukan' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile.id)
      .single();

    if (!employee) {
      return { success: false, error: 'Data karyawan tidak ditemukan' };
    }

    // Check if supervisor has approved
    const { data: permit } = await fromSafetyTable(supabase, 'safety_permits')
      .select('supervisor_approved_by')
      .eq('id', permitId)
      .single();

    if (!permit?.supervisor_approved_by) {
      return { success: false, error: 'Supervisor harus menyetujui terlebih dahulu' };
    }

    const { error } = await fromSafetyTable(supabase, 'safety_permits')
      .update({
        hse_approved_by: employee.id,
        hse_approved_at: new Date().toISOString(),
        status: 'approved',
        updated_at: new Date().toISOString(),
      })
      .eq('id', permitId)
      .eq('status', 'pending');

    if (error) {
      console.error('HSE approval error:', error);
      return { success: false, error: `Gagal menyetujui izin kerja: ${error.message}` };
    }

    revalidatePath('/hse/permits');
    revalidatePath(`/hse/permits/${permitId}`);

    return { success: true };
  } catch (error) {
    console.error('approveByHSE error:', error);
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

/**
 * Activate a permit
 */
export async function activatePermit(
  permitId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    const { error } = await fromSafetyTable(supabase, 'safety_permits')
      .update({
        status: 'active',
        updated_at: new Date().toISOString(),
      })
      .eq('id', permitId)
      .eq('status', 'approved');

    if (error) {
      return { success: false, error: 'Gagal mengaktifkan izin kerja' };
    }

    revalidatePath('/hse/permits');
    revalidatePath(`/hse/permits/${permitId}`);

    return { success: true };
  } catch (error) {
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}


// =====================================================
// PERMIT CLOSURE FUNCTIONS
// =====================================================

/**
 * Close a permit
 */
export async function closePermit(
  permitId: string,
  notes: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (employees.user_id references user_profiles.id)
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (!profile) {
      return { success: false, error: 'Profil pengguna tidak ditemukan' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile.id)
      .single();

    const { error } = await fromSafetyTable(supabase, 'safety_permits')
      .update({
        status: 'completed',
        closed_by: employee?.id || null,
        closed_at: new Date().toISOString(),
        closure_notes: notes,
        updated_at: new Date().toISOString(),
      })
      .eq('id', permitId)
      .eq('status', 'active');

    if (error) {
      console.error('Close permit error:', error);
      return { success: false, error: `Gagal menutup izin kerja: ${error.message}` };
    }

    revalidatePath('/hse/permits');
    revalidatePath(`/hse/permits/${permitId}`);

    return { success: true };
  } catch (error) {
    console.error('closePermit error:', error);
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

/**
 * Cancel a permit
 */
export async function cancelPermit(
  permitId: string,
  reason: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (employees.user_id references user_profiles.id)
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (!profile) {
      return { success: false, error: 'Profil pengguna tidak ditemukan' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile.id)
      .single();

    const { error } = await fromSafetyTable(supabase, 'safety_permits')
      .update({
        status: 'cancelled',
        closed_by: employee?.id || null,
        closed_at: new Date().toISOString(),
        closure_notes: reason,
        updated_at: new Date().toISOString(),
      })
      .eq('id', permitId)
      .in('status', ['pending', 'approved', 'active']);

    if (error) {
      console.error('Cancel permit error:', error);
      return { success: false, error: `Gagal membatalkan izin kerja: ${error.message}` };
    }

    revalidatePath('/hse/permits');
    revalidatePath(`/hse/permits/${permitId}`);

    return { success: true };
  } catch (error) {
    console.error('cancelPermit error:', error);
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

/**
 * Expire permits that have passed their valid_to date
 */
export async function expireOverduePermits(): Promise<{ success: boolean; count?: number; error?: string }> {
  try {
    const supabase = await createClient();

    const now = new Date().toISOString();

    const { data, error } = await fromSafetyTable(supabase, 'safety_permits')
      .update({
        status: 'expired',
        updated_at: now,
      })
      .lt('valid_to', now)
      .in('status', ['pending', 'approved', 'active'])
      .select('id');

    if (error) {
      return { success: false, error: 'Gagal mengupdate izin kadaluarsa' };
    }

    revalidatePath('/hse/permits');

    return { success: true, count: data?.length || 0 };
  } catch (error) {
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}

// =====================================================
// PERMIT STATISTICS
// =====================================================

/**
 * Get permit statistics
 */
export async function getPermitStatistics(): Promise<{
  success: boolean;
  data?: PermitStatistics;
  error?: string;
}> {
  try {
    const supabase = await createClient();

    // Get all permits
    const { data: permits, error } = await fromSafetyTable(supabase, 'safety_permits')
      .select('id, status, permit_type, closed_at');

    if (error) {
      return { success: false, error: 'Gagal mengambil statistik izin kerja' };
    }

    // Calculate statistics
    const byStatus: Record<string, number> = {
      pending: 0,
      approved: 0,
      active: 0,
      completed: 0,
      cancelled: 0,
      expired: 0,
    };

    const byType: Record<string, number> = {
      hot_work: 0,
      confined_space: 0,
      height_work: 0,
      excavation: 0,
      electrical: 0,
      lifting: 0,
    };

    // Count completed this month
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    let completedThisMonth = 0;

    for (const permit of permits || []) {
      // Count by status
      if (permit.status in byStatus) {
        byStatus[permit.status]++;
      }

      // Count by type
      if (permit.permit_type in byType) {
        byType[permit.permit_type]++;
      }

      // Count completed this month
      if (permit.status === 'completed' && permit.closed_at) {
        const closedDate = new Date(permit.closed_at);
        if (closedDate >= startOfMonth) {
          completedThisMonth++;
        }
      }
    }

    return {
      success: true,
      data: {
        totalPermits: permits?.length || 0,
        activePermits: byStatus.active,
        pendingApproval: byStatus.pending,
        completedThisMonth,
        byType: byType as Record<string, number>,
        byStatus: byStatus as Record<string, number>,
      },
    };
  } catch (error) {
    return { success: false, error: `Terjadi kesalahan: ${error instanceof Error ? error.message : 'Unknown error'}` };
  }
}
