'use server';

// =====================================================
// v0.47: HSE - SAFETY DOCUMENTATION SERVER ACTIONS
// =====================================================

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';
import {
  SafetyDocument,
  DocumentCategory,
  JSAHazard,
  DocumentAcknowledgment,
  DocumentStatistics,
  CreateDocumentInput,
  UpdateDocumentInput,
  JSAHazardInput,
  DocumentFilters,
  AcknowledgmentStats,
  SafetyDocumentRow,
  DocumentCategoryRow,
  JSAHazardRow,
  DocumentAcknowledgmentRow,
  transformDocumentRow,
  transformCategoryRow,
  transformHazardRow,
  transformAcknowledgmentRow,
} from '@/types/safety-document';
import {
  validateDocumentInput,
  validateJSAHazardInput,
  getValidityStatus,
  getDaysUntilExpiry,
} from './safety-document-utils';

// Type helper for tables not yet in database.types.ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyTable = any;

// Helper function to bypass type checking for safety document tables
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const fromSafetyTable = (supabase: any, table: string) => supabase.from(table) as AnyTable;

// =====================================================
// DOCUMENT CATEGORIES
// =====================================================

/**
 * Get all active document categories
 */
export async function getDocumentCategories(): Promise<{
  success: boolean;
  data?: DocumentCategory[];
  error?: string;
}> {
  try {
    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'safety_document_categories')
      .select('*')
      .eq('is_active', true)
      .order('display_order', { ascending: true });

    if (error) {
      console.error('Error fetching document categories:', error);
      return { success: false, error: 'Gagal mengambil kategori dokumen' };
    }

    return {
      success: true,
      data: (data as DocumentCategoryRow[]).map(transformCategoryRow),
    };
  } catch (error) {
    console.error('Error in getDocumentCategories:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}


/**
 * Get a single document category by ID
 */
export async function getDocumentCategory(id: string): Promise<{
  success: boolean;
  data?: DocumentCategory;
  error?: string;
}> {
  try {
    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'safety_document_categories')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      console.error('Error fetching document category:', error);
      return { success: false, error: 'Kategori dokumen tidak ditemukan' };
    }

    return {
      success: true,
      data: transformCategoryRow(data as DocumentCategoryRow),
    };
  } catch (error) {
    console.error('Error in getDocumentCategory:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

// =====================================================
// DOCUMENT CRUD OPERATIONS
// =====================================================

/**
 * Create a new safety document
 */
export async function createSafetyDocument(
  input: CreateDocumentInput
): Promise<{ success: boolean; data?: SafetyDocument; error?: string }> {
  try {
    const supabase = await createClient();

    // Get category for validation
    const { data: category } = await fromSafetyTable(supabase, 'safety_document_categories')
      .select('*')
      .eq('id', input.categoryId)
      .single();

    if (!category) {
      return { success: false, error: 'Kategori dokumen tidak ditemukan' };
    }

    // Validate input
    const validation = validateDocumentInput(input, transformCategoryRow(category as DocumentCategoryRow));
    if (!validation.valid) {
      return { success: false, error: validation.error };
    }

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (for FK references to user_profiles) and employee ID
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    // Get employee ID for the user (employees.user_id references user_profiles.id)
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile?.id || '')
      .single();

    // Create document (document_number will be auto-generated by trigger)
    const { data: document, error: insertError } = await fromSafetyTable(supabase, 'safety_documents')
      .insert({
        category_id: input.categoryId,
        title: input.title,
        description: input.description || null,
        content: input.content || null,
        file_url: input.fileUrl || null,
        file_name: input.fileName || null,
        file_type: input.fileType || null,
        applicable_locations: input.applicableLocations || [],
        applicable_departments: input.applicableDepartments || [],
        applicable_job_types: input.applicableJobTypes || [],
        effective_date: input.effectiveDate,
        expiry_date: input.expiryDate || null,
        related_documents: input.relatedDocuments || [],
        requires_acknowledgment: input.requiresAcknowledgment || false,
        prepared_by: employee?.id || null,
        prepared_at: new Date().toISOString(),
        created_by: profile?.id || null,
        status: 'draft',
        version: '1.0',
        revision_number: 1,
      })
      .select()
      .single();

    if (insertError) {
      console.error('Error creating safety document:', insertError);
      return { success: false, error: 'Gagal membuat dokumen keselamatan' };
    }

    revalidatePath('/hse/documents');

    return {
      success: true,
      data: transformDocumentRow(document as SafetyDocumentRow),
    };
  } catch (error) {
    console.error('Error in createSafetyDocument:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Get a safety document by ID
 */
export async function getSafetyDocument(
  id: string
): Promise<{ success: boolean; data?: SafetyDocument; error?: string }> {
  try {
    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'safety_documents')
      .select(`
        *,
        safety_document_categories!inner (category_code, category_name),
        prepared:employees!safety_documents_prepared_by_fkey (full_name),
        reviewed:employees!safety_documents_reviewed_by_fkey (full_name),
        approved:employees!safety_documents_approved_by_fkey (full_name)
      `)
      .eq('id', id)
      .single();

    if (error) {
      console.error('Error fetching safety document:', error);
      return { success: false, error: 'Dokumen tidak ditemukan' };
    }

    // Transform the data
    const document = transformDocumentRow(data as SafetyDocumentRow);
    
    // Add related data
    const category = data.safety_document_categories as { category_code: string; category_name: string };
    const prepared = data.prepared as { full_name: string } | null;
    const reviewed = data.reviewed as { full_name: string } | null;
    const approved = data.approved as { full_name: string } | null;

    document.categoryCode = category.category_code;
    document.categoryName = category.category_name;
    document.preparedByName = prepared?.full_name;
    document.reviewedByName = reviewed?.full_name;
    document.approvedByName = approved?.full_name;
    document.validityStatus = getValidityStatus(document.expiryDate);
    document.daysUntilExpiry = getDaysUntilExpiry(document.expiryDate) ?? undefined;

    return { success: true, data: document };
  } catch (error) {
    console.error('Error in getSafetyDocument:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Get safety documents list with filters
 */
export async function getSafetyDocuments(
  filters: DocumentFilters = {}
): Promise<{ success: boolean; data?: SafetyDocument[]; error?: string }> {
  try {
    const supabase = await createClient();

    let query = fromSafetyTable(supabase, 'safety_documents')
      .select(`
        *,
        safety_document_categories!inner (category_code, category_name),
        prepared:employees!safety_documents_prepared_by_fkey (full_name)
      `)
      .order('created_at', { ascending: false });

    // Apply filters
    if (filters.status) {
      if (Array.isArray(filters.status)) {
        query = query.in('status', filters.status);
      } else {
        query = query.eq('status', filters.status);
      }
    }

    if (filters.categoryId) {
      query = query.eq('category_id', filters.categoryId);
    }

    if (filters.search) {
      query = query.or(`title.ilike.%${filters.search}%,document_number.ilike.%${filters.search}%`);
    }

    if (filters.expiringWithinDays) {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + filters.expiringWithinDays);
      query = query
        .not('expiry_date', 'is', null)
        .lte('expiry_date', futureDate.toISOString().split('T')[0])
        .gte('expiry_date', new Date().toISOString().split('T')[0]);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching safety documents:', error);
      return { success: false, error: 'Gagal mengambil daftar dokumen' };
    }

    // Transform the data
    const documents = (data || []).map((row: SafetyDocumentRow & { 
      safety_document_categories: { category_code: string; category_name: string }; 
      prepared: { full_name: string } | null 
    }) => {
      const document = transformDocumentRow(row as SafetyDocumentRow);
      const category = row.safety_document_categories;
      const prepared = row.prepared;

      document.categoryCode = category.category_code;
      document.categoryName = category.category_name;
      document.preparedByName = prepared?.full_name;
      document.validityStatus = getValidityStatus(document.expiryDate);
      document.daysUntilExpiry = getDaysUntilExpiry(document.expiryDate) ?? undefined;

      return document;
    });

    return { success: true, data: documents };
  } catch (error) {
    console.error('Error in getSafetyDocuments:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Update a safety document
 */
export async function updateSafetyDocument(
  id: string,
  input: UpdateDocumentInput
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Build update object
    const updateData: Record<string, unknown> = {
      updated_at: new Date().toISOString(),
    };

    if (input.title !== undefined) updateData.title = input.title;
    if (input.description !== undefined) updateData.description = input.description;
    if (input.content !== undefined) updateData.content = input.content;
    if (input.fileUrl !== undefined) updateData.file_url = input.fileUrl;
    if (input.fileName !== undefined) updateData.file_name = input.fileName;
    if (input.fileType !== undefined) updateData.file_type = input.fileType;
    if (input.applicableLocations !== undefined) updateData.applicable_locations = input.applicableLocations;
    if (input.applicableDepartments !== undefined) updateData.applicable_departments = input.applicableDepartments;
    if (input.applicableJobTypes !== undefined) updateData.applicable_job_types = input.applicableJobTypes;
    if (input.effectiveDate !== undefined) updateData.effective_date = input.effectiveDate;
    if (input.expiryDate !== undefined) updateData.expiry_date = input.expiryDate;
    if (input.relatedDocuments !== undefined) updateData.related_documents = input.relatedDocuments;
    if (input.requiresAcknowledgment !== undefined) updateData.requires_acknowledgment = input.requiresAcknowledgment;

    const { error } = await fromSafetyTable(supabase, 'safety_documents')
      .update(updateData)
      .eq('id', id);

    if (error) {
      console.error('Error updating safety document:', error);
      return { success: false, error: 'Gagal memperbarui dokumen' };
    }

    revalidatePath('/hse/documents');
    revalidatePath(`/hse/documents/${id}`);

    return { success: true };
  } catch (error) {
    console.error('Error in updateSafetyDocument:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}


// =====================================================
// VERSION CONTROL FUNCTIONS
// =====================================================

/**
 * Create a new version of a document
 */
export async function createNewVersion(
  documentId: string,
  input: CreateDocumentInput
): Promise<{ success: boolean; data?: SafetyDocument; error?: string }> {
  try {
    const supabase = await createClient();

    // Get the current document
    const { data: currentDoc } = await fromSafetyTable(supabase, 'safety_documents')
      .select('*')
      .eq('id', documentId)
      .single();

    if (!currentDoc) {
      return { success: false, error: 'Dokumen tidak ditemukan' };
    }

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get profile ID (for FK references to user_profiles)
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('user_id', user.id)
      .single();

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', profile?.id || '')
      .single();

    // Parse current version and increment
    const currentVersion = parseFloat(currentDoc.version) || 1.0;
    const newVersion = (Math.floor(currentVersion) + 1).toFixed(1);

    // Create new version
    const { data: newDoc, error: insertError } = await fromSafetyTable(supabase, 'safety_documents')
      .insert({
        category_id: input.categoryId,
        title: input.title,
        description: input.description || null,
        content: input.content || null,
        file_url: input.fileUrl || null,
        file_name: input.fileName || null,
        file_type: input.fileType || null,
        applicable_locations: input.applicableLocations || [],
        applicable_departments: input.applicableDepartments || [],
        applicable_job_types: input.applicableJobTypes || [],
        effective_date: input.effectiveDate,
        expiry_date: input.expiryDate || null,
        related_documents: input.relatedDocuments || [],
        requires_acknowledgment: input.requiresAcknowledgment || false,
        prepared_by: employee?.id || null,
        prepared_at: new Date().toISOString(),
        created_by: profile?.id || null,
        status: 'draft',
        version: newVersion,
        revision_number: 1,
        previous_version_id: documentId,
      })
      .select()
      .single();

    if (insertError) {
      console.error('Error creating new version:', insertError);
      return { success: false, error: 'Gagal membuat versi baru' };
    }

    // Mark old version as superseded
    await fromSafetyTable(supabase, 'safety_documents')
      .update({ 
        status: 'superseded',
        updated_at: new Date().toISOString(),
      })
      .eq('id', documentId);

    revalidatePath('/hse/documents');

    return {
      success: true,
      data: transformDocumentRow(newDoc as SafetyDocumentRow),
    };
  } catch (error) {
    console.error('Error in createNewVersion:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

// =====================================================
// APPROVAL WORKFLOW FUNCTIONS
// =====================================================

/**
 * Submit document for review
 */
export async function submitForReview(
  documentId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    const { error } = await fromSafetyTable(supabase, 'safety_documents')
      .update({
        status: 'pending_review',
        updated_at: new Date().toISOString(),
      })
      .eq('id', documentId)
      .eq('status', 'draft');

    if (error) {
      console.error('Error submitting for review:', error);
      return { success: false, error: 'Gagal mengirim untuk review' };
    }

    revalidatePath('/hse/documents');
    revalidatePath(`/hse/documents/${documentId}`);

    return { success: true };
  } catch (error) {
    console.error('Error in submitForReview:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Approve a document
 */
export async function approveDocument(
  documentId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', user.id)
      .single();

    const { error } = await fromSafetyTable(supabase, 'safety_documents')
      .update({
        status: 'approved',
        approved_by: employee?.id || null,
        approved_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', documentId)
      .eq('status', 'pending_review');

    if (error) {
      console.error('Error approving document:', error);
      return { success: false, error: 'Gagal menyetujui dokumen' };
    }

    revalidatePath('/hse/documents');
    revalidatePath(`/hse/documents/${documentId}`);

    return { success: true };
  } catch (error) {
    console.error('Error in approveDocument:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Reject a document (return to draft)
 */
export async function rejectDocument(
  documentId: string,
  reason: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', user.id)
      .single();

    const { error } = await fromSafetyTable(supabase, 'safety_documents')
      .update({
        status: 'draft',
        reviewed_by: employee?.id || null,
        reviewed_at: new Date().toISOString(),
        description: reason, // Store rejection reason in description temporarily
        updated_at: new Date().toISOString(),
      })
      .eq('id', documentId)
      .eq('status', 'pending_review');

    if (error) {
      console.error('Error rejecting document:', error);
      return { success: false, error: 'Gagal menolak dokumen' };
    }

    revalidatePath('/hse/documents');
    revalidatePath(`/hse/documents/${documentId}`);

    return { success: true };
  } catch (error) {
    console.error('Error in rejectDocument:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}


// =====================================================
// ACKNOWLEDGMENT FUNCTIONS
// =====================================================

/**
 * Acknowledge a document
 */
export async function acknowledgeDocument(
  documentId: string,
  quizScore?: number
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return { success: false, error: 'User tidak terautentikasi' };
    }

    // Get employee ID
    const { data: employee } = await supabase
      .from('employees')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (!employee) {
      return { success: false, error: 'Profil karyawan tidak ditemukan' };
    }

    // Check if already acknowledged
    const { data: existing } = await fromSafetyTable(supabase, 'safety_document_acknowledgments')
      .select('id')
      .eq('document_id', documentId)
      .eq('employee_id', employee.id)
      .single();

    if (existing) {
      return { success: false, error: 'Dokumen sudah diakui sebelumnya' };
    }

    // Create acknowledgment
    const { error } = await fromSafetyTable(supabase, 'safety_document_acknowledgments')
      .insert({
        document_id: documentId,
        employee_id: employee.id,
        acknowledged_at: new Date().toISOString(),
        quiz_score: quizScore ?? null,
        quiz_passed: quizScore !== undefined ? quizScore >= 70 : null,
      });

    if (error) {
      console.error('Error acknowledging document:', error);
      return { success: false, error: 'Gagal mengakui dokumen' };
    }

    revalidatePath(`/hse/documents/${documentId}`);

    return { success: true };
  } catch (error) {
    console.error('Error in acknowledgeDocument:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Get document acknowledgments
 */
export async function getDocumentAcknowledgments(
  documentId: string
): Promise<{ success: boolean; data?: DocumentAcknowledgment[]; error?: string }> {
  try {
    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'safety_document_acknowledgments')
      .select(`
        *,
        employees (full_name)
      `)
      .eq('document_id', documentId)
      .order('acknowledged_at', { ascending: false });

    if (error) {
      console.error('Error fetching acknowledgments:', error);
      return { success: false, error: 'Gagal mengambil daftar pengakuan' };
    }

    const acknowledgments = (data || []).map((row: DocumentAcknowledgmentRow & { employees: { full_name: string } | null }) => {
      const ack = transformAcknowledgmentRow(row as DocumentAcknowledgmentRow);
      ack.employeeName = row.employees?.full_name;
      return ack;
    });

    return { success: true, data: acknowledgments };
  } catch (error) {
    console.error('Error in getDocumentAcknowledgments:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Get acknowledgment statistics for a document
 */
export async function getAcknowledgmentStats(
  documentId: string
): Promise<{ success: boolean; data?: AcknowledgmentStats; error?: string }> {
  try {
    const supabase = await createClient();

    // Get total employees count
    const { count: totalEmployees } = await supabase
      .from('employees')
      .select('*', { count: 'exact', head: true })
      .eq('status', 'active');

    // Get acknowledgment count
    const { count: acknowledged } = await fromSafetyTable(supabase, 'safety_document_acknowledgments')
      .select('*', { count: 'exact', head: true })
      .eq('document_id', documentId);

    const total = totalEmployees || 0;
    const acked = acknowledged || 0;
    const rate = total > 0 ? Math.round((acked / total) * 100) : 0;

    return {
      success: true,
      data: {
        totalRequired: total,
        totalAcknowledged: acked,
        completionRate: rate,
      },
    };
  } catch (error) {
    console.error('Error in getAcknowledgmentStats:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}


// =====================================================
// JSA HAZARD FUNCTIONS
// =====================================================

/**
 * Add a JSA hazard to a document
 */
export async function addJSAHazard(
  documentId: string,
  hazard: JSAHazardInput
): Promise<{ success: boolean; data?: JSAHazard; error?: string }> {
  try {
    // Validate input
    const validation = validateJSAHazardInput(hazard);
    if (!validation.valid) {
      return { success: false, error: validation.error };
    }

    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'jsa_hazards')
      .insert({
        document_id: documentId,
        step_number: hazard.stepNumber,
        work_step: hazard.workStep,
        hazards: hazard.hazards,
        consequences: hazard.consequences || null,
        risk_level: hazard.riskLevel || null,
        control_measures: hazard.controlMeasures,
        responsible: hazard.responsible || null,
      })
      .select()
      .single();

    if (error) {
      console.error('Error adding JSA hazard:', error);
      return { success: false, error: 'Gagal menambahkan bahaya JSA' };
    }

    revalidatePath(`/hse/documents/${documentId}`);

    return {
      success: true,
      data: transformHazardRow(data as JSAHazardRow),
    };
  } catch (error) {
    console.error('Error in addJSAHazard:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Update a JSA hazard
 */
export async function updateJSAHazard(
  hazardId: string,
  hazard: JSAHazardInput
): Promise<{ success: boolean; error?: string }> {
  try {
    // Validate input
    const validation = validateJSAHazardInput(hazard);
    if (!validation.valid) {
      return { success: false, error: validation.error };
    }

    const supabase = await createClient();

    const { error } = await fromSafetyTable(supabase, 'jsa_hazards')
      .update({
        step_number: hazard.stepNumber,
        work_step: hazard.workStep,
        hazards: hazard.hazards,
        consequences: hazard.consequences || null,
        risk_level: hazard.riskLevel || null,
        control_measures: hazard.controlMeasures,
        responsible: hazard.responsible || null,
        updated_at: new Date().toISOString(),
      })
      .eq('id', hazardId);

    if (error) {
      console.error('Error updating JSA hazard:', error);
      return { success: false, error: 'Gagal memperbarui bahaya JSA' };
    }

    revalidatePath('/hse/documents');

    return { success: true };
  } catch (error) {
    console.error('Error in updateJSAHazard:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Delete a JSA hazard
 */
export async function deleteJSAHazard(
  hazardId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = await createClient();

    const { error } = await fromSafetyTable(supabase, 'jsa_hazards')
      .delete()
      .eq('id', hazardId);

    if (error) {
      console.error('Error deleting JSA hazard:', error);
      return { success: false, error: 'Gagal menghapus bahaya JSA' };
    }

    revalidatePath('/hse/documents');

    return { success: true };
  } catch (error) {
    console.error('Error in deleteJSAHazard:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Get JSA hazards for a document
 */
export async function getJSAHazards(
  documentId: string
): Promise<{ success: boolean; data?: JSAHazard[]; error?: string }> {
  try {
    const supabase = await createClient();

    const { data, error } = await fromSafetyTable(supabase, 'jsa_hazards')
      .select('*')
      .eq('document_id', documentId)
      .order('step_number', { ascending: true });

    if (error) {
      console.error('Error fetching JSA hazards:', error);
      return { success: false, error: 'Gagal mengambil daftar bahaya JSA' };
    }

    return {
      success: true,
      data: (data as JSAHazardRow[]).map(transformHazardRow),
    };
  } catch (error) {
    console.error('Error in getJSAHazards:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}


// =====================================================
// STATISTICS FUNCTIONS
// =====================================================

/**
 * Get document statistics
 */
export async function getDocumentStatistics(): Promise<{
  success: boolean;
  data?: DocumentStatistics;
  error?: string;
}> {
  try {
    const supabase = await createClient();

    // Get all documents
    const { data: documents, error } = await fromSafetyTable(supabase, 'safety_documents')
      .select(`
        id,
        status,
        category_id,
        expiry_date,
        safety_document_categories!inner (category_code)
      `);

    if (error) {
      console.error('Error fetching document statistics:', error);
      return { success: false, error: 'Gagal mengambil statistik dokumen' };
    }

    // Calculate statistics
    const byStatus: Record<string, number> = {
      draft: 0,
      pending_review: 0,
      approved: 0,
      expired: 0,
      superseded: 0,
      archived: 0,
    };

    const byCategory: Record<string, number> = {};
    let expiringWithin30Days = 0;

    const now = new Date();
    const thirtyDaysFromNow = new Date();
    thirtyDaysFromNow.setDate(thirtyDaysFromNow.getDate() + 30);

    for (const doc of documents || []) {
      // Count by status
      if (doc.status in byStatus) {
        byStatus[doc.status]++;
      }

      // Count by category
      const categoryCode = (doc.safety_document_categories as { category_code: string }).category_code;
      byCategory[categoryCode] = (byCategory[categoryCode] || 0) + 1;

      // Count expiring documents
      if (doc.expiry_date && doc.status !== 'archived' && doc.status !== 'superseded') {
        const expiryDate = new Date(doc.expiry_date);
        if (expiryDate >= now && expiryDate <= thirtyDaysFromNow) {
          expiringWithin30Days++;
        }
      }
    }

    return {
      success: true,
      data: {
        totalDocuments: documents?.length || 0,
        approvedDocuments: byStatus.approved,
        pendingReview: byStatus.pending_review,
        expiringWithin30Days,
        byCategory,
        byStatus: byStatus as Record<string, number>,
      },
    };
  } catch (error) {
    console.error('Error in getDocumentStatistics:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}

/**
 * Get expiring documents
 */
export async function getExpiringDocuments(
  days: number = 30
): Promise<{ success: boolean; data?: SafetyDocument[]; error?: string }> {
  try {
    const supabase = await createClient();

    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + days);

    const { data, error } = await fromSafetyTable(supabase, 'safety_documents')
      .select(`
        *,
        safety_document_categories!inner (category_code, category_name),
        prepared:employees!safety_documents_prepared_by_fkey (full_name)
      `)
      .not('expiry_date', 'is', null)
      .lte('expiry_date', futureDate.toISOString().split('T')[0])
      .not('status', 'in', '("archived","superseded")')
      .order('expiry_date', { ascending: true });

    if (error) {
      console.error('Error fetching expiring documents:', error);
      return { success: false, error: 'Gagal mengambil dokumen yang akan kadaluarsa' };
    }

    const documents = (data || []).map((row: SafetyDocumentRow & { 
      safety_document_categories: { category_code: string; category_name: string }; 
      prepared: { full_name: string } | null 
    }) => {
      const document = transformDocumentRow(row as SafetyDocumentRow);
      const category = row.safety_document_categories;
      const prepared = row.prepared;

      document.categoryCode = category.category_code;
      document.categoryName = category.category_name;
      document.preparedByName = prepared?.full_name;
      document.validityStatus = getValidityStatus(document.expiryDate);
      document.daysUntilExpiry = getDaysUntilExpiry(document.expiryDate) ?? undefined;

      return document;
    });

    return { success: true, data: documents };
  } catch (error) {
    console.error('Error in getExpiringDocuments:', error);
    return { success: false, error: 'Terjadi kesalahan' };
  }
}
