// Export Utility Functions for Reports

import { DateRange } from '@/types/reports'

export interface ExportColumn {
  key: string
  header: string
  format?: 'currency' | 'percentage' | 'number' | 'date' | 'text'
}

export interface ExportMetadata {
  generatedAt: Date
  generatedBy: string
  reportTitle: string
  period?: DateRange
}

export interface ExportOptions {
  reportTitle: string
  columns: ExportColumn[]
  data: Record<string, unknown>[]
  metadata: ExportMetadata
  summary?: { label: string; value: string | number }[]
}

/**
 * Format value based on column format type
 */
export function formatExportValue(value: unknown, format?: ExportColumn['format']): string | number {
  if (value === null || value === undefined) return ''
  
  switch (format) {
    case 'currency':
      return typeof value === 'number' ? value : parseFloat(String(value)) || 0
    case 'percentage':
      return typeof value === 'number' ? `${value.toFixed(1)}%` : String(value)
    case 'number':
      return typeof value === 'number' ? value : parseFloat(String(value)) || 0
    case 'date':
      if (value instanceof Date) {
        return value.toLocaleDateString('id-ID')
      }
      return String(value)
    default:
      return String(value)
  }
}

/**
 * Format data for export
 */
export function formatExportData(
  data: Record<string, unknown>[],
  columns: ExportColumn[]
): Record<string, string | number>[] {
  return data.map(row => {
    const formattedRow: Record<string, string | number> = {}
    for (const col of columns) {
      formattedRow[col.header] = formatExportValue(row[col.key], col.format)
    }
    return formattedRow
  })
}

/**
 * Generate Excel report
 */
export async function generateExcelReport(options: ExportOptions): Promise<Blob> {
  const { reportTitle, columns, data, metadata, summary } = options

  const ExcelJSModule = await import('exceljs')
  const ExcelJSLib = ExcelJSModule.default
  const workbook = new ExcelJSLib.Workbook()
  const worksheet = workbook.addWorksheet('Report')
  
  let currentRow = 1
  
  // Add header rows with metadata
  worksheet.getCell(`A${currentRow}`).value = reportTitle
  worksheet.getCell(`A${currentRow}`).font = { bold: true, size: 14 }
  currentRow++
  
  worksheet.getCell(`A${currentRow}`).value = `Generated: ${metadata.generatedAt.toLocaleString('id-ID')}`
  currentRow++
  
  worksheet.getCell(`A${currentRow}`).value = `Generated by: ${metadata.generatedBy}`
  currentRow++
  
  if (metadata.period) {
    worksheet.getCell(`A${currentRow}`).value = 
      `Period: ${metadata.period.startDate.toLocaleDateString('id-ID')} - ${metadata.period.endDate.toLocaleDateString('id-ID')}`
    currentRow++
  }
  
  currentRow++ // Empty row
  
  // Add summary if provided
  if (summary && summary.length > 0) {
    worksheet.getCell(`A${currentRow}`).value = 'Summary'
    worksheet.getCell(`A${currentRow}`).font = { bold: true }
    currentRow++
    
    for (const item of summary) {
      worksheet.getCell(`A${currentRow}`).value = item.label
      worksheet.getCell(`B${currentRow}`).value = String(item.value)
      currentRow++
    }
    currentRow++ // Empty row
  }
  
  // Add column headers
  const headerRow = worksheet.getRow(currentRow)
  columns.forEach((col, index) => {
    const cell = headerRow.getCell(index + 1)
    cell.value = col.header
    cell.font = { bold: true }
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' }
    }
  })
  currentRow++
  
  // Add data rows
  const formattedData = formatExportData(data, columns)
  for (const row of formattedData) {
    const dataRow = worksheet.getRow(currentRow)
    columns.forEach((col, index) => {
      dataRow.getCell(index + 1).value = row[col.header]
    })
    currentRow++
  }
  
  // Auto-fit columns
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  worksheet.columns.forEach((column: any) => {
    column.width = 15
  })
  
  // Generate blob
  const buffer = await workbook.xlsx.writeBuffer()
  return new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

/**
 * Download file helper
 */
export function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Generate and download Excel report
 */
export async function downloadExcelReport(options: ExportOptions, filename?: string): Promise<void> {
  const blob = await generateExcelReport(options)
  const defaultFilename = `${options.reportTitle.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.xlsx`
  downloadFile(blob, filename || defaultFilename)
}

/**
 * Check if export metadata is valid
 */
export function validateExportMetadata(metadata: ExportMetadata): boolean {
  return !!(
    metadata.generatedAt instanceof Date &&
    metadata.generatedBy &&
    metadata.reportTitle
  )
}
